FROM ubuntu
RUN apt-get update
RUN apt-get -y install build-essential git cmake apt-utils
RUN git clone https://github.com/opencv/opencv
RUN cd opencv/ && git checkout 3.4
RUN apt-get install -y software-properties-common 
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections && apt-get install -y oracle-java8-installer
RUN apt-get install -y java-wrappers junit ant maven openjdk-8-jdk
RUN cd opencv/  && mkdir build && cd build/ && cmake -D BUILD_SHARED_LIBS=OFF ..&& make -j12
RUN cd opencv/build  && mvn install:install-file -Dfile=./bin/opencv-346.jar -DgroupId=org.opencv -DartifactId=opencv -Dversion=3.4.6 -Dpackaging=jar
RUN git clone https://github.com/JulieFournier/ESIRTPDockerSampleApp/
RUN cd ESIRTPDockerSampleApp/ && mvn package
VOLUME opencv /opencv
VOLUME ESIRTPDockerSampleApp /ESIRTPDockerSampleApp
